### ISSUE TITLE
 Index was outside the bounds of the array( connecting to redis 2.8.12 version)

### ISSUE THREAD

**Issue by NareshBanala** [chakrit/sider#22]
Index was outside the bounds of the array.

Stack trace
at Sider.RedisClient`1.<Info>m__D(ProtocolReader r)
at Sider.RedisClient`1.<invoke>c__AnonStorey5B`1.<>m__1(ProtocolReader r)
at Sider.Executors.ExecutorBase.ExecuteImmediate[T](Invocation`1 invocation)
at Sider.Executors.ImmediateExecutor.execute[T](Invocation`1 invocation, Int32 retryCount)
at Sider.Executors.ImmediateExecutor.Execute[T](Invocation`1 invocation)
at Sider.RedisClient`1.invoke[TInv](Invocation`1 invocation)
at Sider.RedisClient`1.invoke[TInv](String command, Int32 numArgs, Action`1 writeArgsAction, Func`2 readAction)
at Sider.RedisClient`1.invoke[TInv](String command, Func`2 readAction)
at Sider.RedisClient`1.Info()

**Comment by chakrit** [comment]
Fixed by #21
